### ISSUE TITLE
Could not find a JavaScript runtim

### ISSUE THREAD

**Issue by vitalsignapp** [joshlarsen/jekyll4-deploy-gh-pages#3]
The Error show in build process

<img width="515" alt="Screen Shot 2020-04-15 at 10 28 42" src="https://user-images.githubusercontent.com/62788697/79295978-5459f600-7f04-11ea-8eda-a96b8146cd5b.png">

```
Building Jekyll site...
bundler: failed to load command: jekyll (/github/workspace/vendor/bundle/ruby/2.6.0/bin/jekyll)
ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes.
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/autoprefixer-rails-9.7.6/lib/autoprefixer-rails/processor.rb:2:in `require'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/autoprefixer-rails-9.7.6/lib/autoprefixer-rails/processor.rb:2:in `<top (required)>'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/autoprefixer-rails-9.7.6/lib/autoprefixer-rails.rb:39:in `require_relative'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/autoprefixer-rails-9.7.6/lib/autoprefixer-rails.rb:39:in `<top (required)>'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-autoprefixer-1.0.2/lib/jekyll/autoprefixer/autoprefixer.rb:4:in `require'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-autoprefixer-1.0.2/lib/jekyll/autoprefixer/autoprefixer.rb:4:in `<top (required)>'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-autoprefixer-1.0.2/lib/jekyll/autoprefixer.rb:8:in `require_relative'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-autoprefixer-1.0.2/lib/jekyll/autoprefixer.rb:8:in `<module:Autoprefixer>'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-autoprefixer-1.0.2/lib/jekyll/autoprefixer.rb:5:in `<module:Jekyll>'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-autoprefixer-1.0.2/lib/jekyll/autoprefixer.rb:4:in `<top (required)>'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-autoprefixer-1.0.2/lib/jekyll-autoprefixer.rb:7:in `require_relative'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-autoprefixer-1.0.2/lib/jekyll-autoprefixer.rb:7:in `<top (required)>'
  /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `require'
```

Is it possible to add ExecJS Runtime for build jekyll

**Comment by joshlarsen** [comment]
Unfortunately, I don't have a Jekyll site that uses ExecJS, so I have no way to test this. The easiest path forward is probably to fork this repo and update the `Dockerfile` as follows:

```Dockerfile
FROM ruby:2.6.5

# install node for ExecJS support
RUN apt-get update && apt-get install -y nodejs

# install a modern bundler version
RUN gem install bundler

ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
```

Then reference your custom action.

**Comment by vitalsignapp** [comment]
Thank you 🤟
