### ISSUE TITLE
bundler: failed to load command

### ISSUE THREAD

**Issue by judsonlmoore** [joshlarsen/jekyll4-deploy-gh-pages#5]
Thanks for this action, it's really great and works perfectly on a few repos I have but [in this repo](https://github.com/BaurJoe/WithoutAPath) I've been getting an error over and over that I can't figure out how to resolve: 

`bundler: failed to load command: jekyll (/github/workspace/vendor/bundle/ruby/2.6.0/bin/jekyll)`

I forked the action so that I could add `--trace` to the `build` but this also didn't reveal a path to a solution for me. Any ideas where the error is originating? 

Here is the rest of the error output with the trace: 

```
Building Jekyll site...
Configuration file: /github/workspace/_config.yml
            Source: /github/workspace
       Destination: /github/workspace/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
         AutoPages: Generating tags pages
         AutoPages: Generating categories pages
         AutoPages: Generating collections pages
        Pagination: Complete, processed 83 pagination page(s)
       Jekyll Feed: Generating feed for posts
bundler: failed to load command: jekyll (/github/workspace/vendor/bundle/ruby/2.6.0/bin/jekyll)
Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/url.rb:158:in `encode'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/url.rb:158:in `unescape_path'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/static_file.rb:58:in `destination'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/cleaner.rb:60:in `block (2 levels) in new_files'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:344:in `block (2 levels) in each_site_file'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:343:in `each'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:342:in `each_site_file'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/cleaner.rb:60:in `block in new_files'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/cleaner.rb:59:in `tap'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/cleaner.rb:59:in `new_files'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/cleaner.rb:25:in `obsolete_files'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/cleaner.rb:15:in `cleanup!'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:211:in `cleanup'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/site.rb:77:in `process'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /github/workspace/vendor/bundle/ruby/2.6.0/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
  /github/workspace/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `load'
  /github/workspace/vendor/bundle/ruby/2.6.0/bin/jekyll:23:in `<top (required)>'
```

**Comment by joshlarsen** [comment]
It looks like a Jekyll specific error. Check out [this thread](https://github.com/jekyll/jekyll/issues/8120). There is monkey patch plugin suggestion to troubleshoot which exact file is throwing the error.

I don't think this is related to the Action, so I am going to close the issue. Feel free to re-open if you find something that points to this action being the culprit. Thx.
